global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/prometheus-alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ingest-api'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'aggregator'
    static_configs:
      - targets: ['host.docker.internal:8082']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'diagnoser'
    static_configs:
      - targets: ['host.docker.internal:8083']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']